% load audio

[x,Fs] = audioread('../test/zapsplat_1.wav');

% create augmenter object

augmenter = audioDataAugmenter(...
    "AugmentationMode","sequential", ...
    "AugmentationParameterSource","random",...
    "NumAugmentations",100, ...
    ...
    "TimeStretchProbability",1, ...
    "SpeedupFactorRange", [0.6,1.6], ...
    ...
    "PitchShiftProbability",0, ...
    ...
    "VolumeControlProbability",0, ...
    "VolumeGainRange",[-5,5], ... % in dB
    ...
    "AddNoiseProbability",0, ...
    "SNRRange",[0,10],... % in dB
    ...
    "TimeShiftProbability",0, ...
    "TimeShiftRange", [-500e-3,500e-3]); % in seconds

% augment audio

x_aug = augment(augmenter,x,Fs);

for i = 1:height(x_aug)
    disp(x_aug.AugmentationInfo(i))
end
% for i=1:height(x_aug)
%     audiowrite('.../test/zapsplate_1')
% end